Feature/7.3.1 core upgrade (#134)
* upgrade karaf to 4.2.7

* replace 4.2.4 jar by 4.2.7 in endorsed

* format

* correct spring_security version

* remove patch for TESB-25565

* remove patch for TESB-25795

* Upgrade CXF to 3.3.4

* remove patch for TESB-25073

* TESB-27232 Upgrade ActiveMQ 5.15.10

* remove patch for TESB-25945

* remove useless code

* modify the comment

* remove patch for TESB-25945

* TESB-27232 fix the failed test case in camel-jmx example

* fix pb in java11 launch

* revert pr 125

* remove patch TESB-25945(cxf-rt-transports-http-jetty

* Upgrade CXF to 3.3.4

* upgrade leftover

* TESB-27208 : Upgrade to Camel 2.24.2

* TESB-27154 - Update Jackson to 2.10.0

* TESB-27154 Upgrade to Jackson 2.10.0 in SE Runtime

* TESB-27192 TESB-27222 tSoap component throw NoClassDefFoundError error when deployed in runtime

* TESB-25393 TESB-27222 remove the patch for org.apache.aries.blueprint.core

* TESB-27208 sync the CXF version in Camel feature xml

* TESB-26759 - Update Commons BeanUtils

* TESB-27214 patch the apache-cxf-3.3.4-features.xml for CXF-8160/CXF-8155

* TESB-27214 sync the wss4j version to 2.2.4